name: CD/CI
run-name: Build Job ${{ github.event.head_commit.message }} by @${{ github.actor }}
env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
on:
  push:
    branches:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  workflow-pkgbuilder:
    uses: frefolli/workflow-pkgbuilder/.github/workflows/release.yml@master
    with:
      version: "v${{ github.head_ref || github.ref_name }}"
    secrets:
      github-token: "${{ secrets.GITHUB_TOKEN }}"
